### ISSUE TITLE
update sample code for 7.0.0 release removing set_sdk_key

### ISSUE THREAD

**Issue by jconsidi** [launchdarkly/hello-python#8]
The 7.0.0 release removed set_sdk_key, but this example and https://docs.launchdarkly.com/sdk/server-side/python still use it.

**Comment by eli-darkly** [comment]
This was fixed by https://github.com/launchdarkly/hello-python/pull/9.

**Comment by eli-darkly** [comment]
Oh, wait, sorry - this issue is referring to the online docs, not to the repository the issue was filed on. Well, it's still not an issue for this repository so I'll leave it closed, but we are fixing the docs.

**Comment by eli-darkly** [comment]
The issue and PR for the online docs are https://github.com/launchdarkly/LaunchDarkly-Docs/issues/101 and https://github.com/launchdarkly/LaunchDarkly-Docs/pull/99.
